# Generated by Django 6.0.2 on 2026-02-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('post', models.CharField(max_length=255)),
                ('dist', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=255)),
                ('logo', models.FileField(blank=True, null=True, upload_to='company_logos/')),
                ('gst', models.CharField(max_length=50)),
                ('reg_date', models.DateField(blank=True, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
