# Generated by Django 6.0.2 on 2026-02-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
