# Generated by Django 6.0.2 on 2026-02-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0002_company_company_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('post', models.CharField(max_length=255)),
                ('dist', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=255)),
                ('reg_date', models.DateField(blank=True, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
