# Generated by Django 6.0 on 2026-02-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0005_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('post', models.CharField(max_length=255)),
                ('dist', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='patient_photos/')),
                ('adhar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('reg_date', models.DateField(blank=True, null=True)),
                ('referred_by', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
            ],
        ),
    ]
