# Generated by Django 6.0 on 2026-02-14 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0006_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icode', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('location1', models.CharField(blank=True, max_length=255, null=True)),
                ('location2', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dosage', models.CharField(blank=True, max_length=255, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('instock', 'In Stock'), ('out_of_stock', 'Out Of Stock')], default='instock', max_length=20)),
                ('hsn_code', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.FileField(blank=True, null=True, upload_to='item_images/')),
                ('img2', models.FileField(blank=True, null=True, upload_to='item_images/')),
                ('img3', models.FileField(blank=True, null=True, upload_to='item_images/')),
                ('img4', models.FileField(blank=True, null=True, upload_to='item_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='item_videos/')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='newlogin.item')),
            ],
        ),
    ]
