# Generated by Django 6.0 on 2026-02-14 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0007_item_itemmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_code', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('count', models.PositiveIntegerField(default=0)),
                ('location1', models.CharField(blank=True, max_length=255, null=True)),
                ('location2', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dosage', models.CharField(blank=True, max_length=255, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in stock', 'In Stock'), ('out of stock', 'Out of Stock')], default='in stock', max_length=20)),
                ('hsn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemmedia',
            name='item',
        ),
        migrations.CreateModel(
            name='MedicineMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.FileField(blank=True, null=True, upload_to='medicine_images/')),
                ('img2', models.FileField(blank=True, null=True, upload_to='medicine_images/')),
                ('img3', models.FileField(blank=True, null=True, upload_to='medicine_images/')),
                ('img4', models.FileField(blank=True, null=True, upload_to='medicine_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='medicine_videos/')),
                ('medicine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='newlogin.medicine')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemMedia',
        ),
    ]
