# Generated by Django 6.0 on 2026-02-14 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0008_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='count',
        ),
    ]
