# Generated by Django 6.0 on 2026-02-16 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0009_remove_medicine_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('lr_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('batch_no', models.CharField(blank=True, max_length=100, null=True)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchasing_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('purchase_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='newlogin.purchasebill')),
            ],
        ),
    ]
