# Generated by Django 6.0 on 2026-02-18 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0010_purchase_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebillitem',
            name='purchase_bill',
        ),
        migrations.DeleteModel(
            name='PurchaseBill',
        ),
        migrations.DeleteModel(
            name='PurchaseBillItem',
        ),
    ]
