# Generated by Django 6.0 on 2026-02-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0011_remove_purchase_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catcode', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='category_images/')),
            ],
        ),
    ]
