# Generated by Django 6.0 on 2026-02-19 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0013_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_no', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='newlogin.staff')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='newlogin.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_code', models.CharField(blank=True, max_length=50, null=True)),
                ('sku_code', models.CharField(blank=True, max_length=100, null=True)),
                ('sku_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_type', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('full_quantity', models.PositiveIntegerField(default=0)),
                ('actual_quantity', models.PositiveIntegerField(default=0)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='newlogin.purchaseorder')),
            ],
        ),
    ]
