# Generated by Django 6.0 on 2026-02-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0014_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='item_type',
            field=models.CharField(blank=True, choices=[('p&p', 'P&P'), ('shedule1', 'Shedule1')], max_length=20, null=True),
        ),
    ]
