# Generated by Django 6.0 on 2026-02-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0015_purchase_order_item_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('partially delived', 'Partially Delived'), ('full delived', 'Full Delived')], default='issued', max_length=20),
        ),
    ]
