# Generated by Django 6.0 on 2026-02-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0019_item_and_item_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
