# Generated by Django 6.0 on 2026-02-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0020_item_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customer_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
