# Generated by Django 6.0 on 2026-02-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0021_userprofile_customer_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('ccode', models.CharField(blank=True, max_length=50, null=True)),
                ('inv_no', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('courier_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('despatch_no', models.CharField(blank=True, max_length=100, null=True)),
                ('courier', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_status', models.CharField(default='CART', max_length=20)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
