# Generated by Django 6.0 on 2026-02-22 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0022_cart_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_code', models.CharField(max_length=100)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='newlogin.cart')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('cart', 'm_code')},
            },
        ),
    ]
