# Generated by Django 6.0 on 2026-02-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0023_online_order_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlineorderitem',
            old_name='m_code',
            new_name='item_code',
        ),
        migrations.AlterUniqueTogether(
            name='onlineorderitem',
            unique_together={('cart', 'item_code')},
        ),
    ]
