# Generated by Django 6.0 on 2026-02-22 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0024_rename_m_code_onlineorderitem_item_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='m_code',
            new_name='item_code',
        ),
    ]
