# Generated by Django 6.0 on 2026-02-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0025_purchaseorderitem_m_code_to_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cart-level discount amount (e.g. applied at checkout).', max_digits=12),
        ),
    ]
