# Generated by Django 6.0 on 2026-02-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0027_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_mode',
            field=models.CharField(blank=True, help_text='e.g. COD, ONLINE; set on order confirm.', max_length=20, null=True),
        ),
    ]
