# Generated by Django 6.0 on 2026-02-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0029_onetimepassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='customer_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='is_new_customer',
            field=models.BooleanField(default=True),
        ),
    ]
