# Generated by Django 6.0 on 2026-02-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0030_onetimepassword_customer_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='is_new_customer',
        ),
    ]
