# Generated by Django 6.0 on 2026-02-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0031_remove_onetimepassword_is_new_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
