# Generated by Django 6.0 on 2026-02-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0035_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
