# Generated by Django 6.0 on 2026-02-27 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0036_alter_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcode', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('sku_name', models.CharField(max_length=255)),
                ('sku_code', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(max_length=50)),
                ('unit_prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('prefix_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('catcode', models.CharField(blank=True, max_length=20, null=True)),
                ('package_count', models.PositiveIntegerField(default=1)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sell_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('storage_location1', models.CharField(blank=True, max_length=255, null=True)),
                ('storage_location2', models.CharField(blank=True, max_length=255, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dosage_instructions', models.TextField(blank=True, null=True)),
                ('basic_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalItemMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.CharField(blank=True, max_length=500, null=True)),
                ('img2', models.CharField(blank=True, max_length=500, null=True)),
                ('img3', models.CharField(blank=True, max_length=500, null=True)),
                ('img4', models.CharField(blank=True, max_length=500, null=True)),
                ('video_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='newlogin.medicalitem')),
            ],
        ),
    ]
