# Generated by Django 6.0 on 2026-02-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0037_medicalitem_medicalitemmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalitemmedia',
            name='medical_item',
        ),
        migrations.DeleteModel(
            name='MedicalItem',
        ),
        migrations.DeleteModel(
            name='MedicalItemMedia',
        ),
    ]
