# Generated by Django 6.0 on 2026-02-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlogin', '0039_medicalitem_medicalitemmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('promo_start', models.DateField(blank=True, null=True)),
                ('promo_end', models.DateField(blank=True, null=True)),
                ('discount_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('type', models.CharField(choices=[('existing', 'Existing'), ('new', 'New')], default='new', max_length=20)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
